version: "3.3"

services:
  react-app:
    image: react-app
    restart: always
    build:
      context: .
    ports:
      - 8080:3000
    networks:
      - simulaciones

networks:
  simulaciones:
    external: true
